projet/librairie/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('accueil/', views.home),
    path('article/<id_article>', views.view_article),
    path('addition/<int:nombre1>/<int:nombre2>/', views.addition),
    path('contact/', views.contact, name='contact'),
    path('livre/', views.livre, name='livre'),
    path('livreDetails/<int:id>', views.livreDetails, name='livreDetails'),
]

projet/projet/urls.py
from django.contrib import admin
from django.urls import path, include
from librairie import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('librairie/', include('librairie.urls')),
]

projet/librairie/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

# Create your models here.


class Livre(models.Model):
    titre = models.CharField(max_length=100)
    auteur = models.CharField(max_length=42)
    resume = models.TextField(null=True)
    date = models.DateTimeField(default=timezone.now, 
                                verbose_name="Date de parution")
    categorie = models.ForeignKey('Categorie', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="photos/")
    

    
    class Meta:
        
        verbose_name = "livre"
        ordering = ['date']
        
    
    def __str__(self):
        """ 
        Cette méthode que nous définirons dans tous les modèles
        nous permettra de reconnaître facilement les différents objets que 
        nous traiterons plus tard dans l'administration
        """
        return self.titre

class Categorie(models.Model):
    nom = models.CharField(max_length=30, default="", editable=False)

    def __str__(self):
        return self.nom

projet/librairie/forms.py
from django import forms
from .models import Livre

class ContactForm(forms.Form):
    sujet = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    envoyeur = forms.EmailField(label="Votre adresse e-mail")
    renvoi = forms.BooleanField(help_text="Cochez si vous souhaitez obtenir une copie du mail envoyé.", required=False)

class LivreForm(forms.ModelForm):
    class Meta:
        model = Livre
        fields = '__all__'
        photo = forms.ImageField()

projet/librairie/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.shortcuts import redirect
from datetime import datetime
from .forms import ContactForm
from .forms import LivreForm
from librairie.models import Livre

def home(request):
    livres = Livre.objects.all() # Nous sélectionnons tous nos articles
    return render(request, 'librairie/accueil.html', {'derniers_livre': livres})
 
    
def view_article(request, id_article):
    """ 
    Vue qui affiche un article selon son identifiant (ou ID, ici un numéro)
    Son ID est le second paramètre de la fonction (pour rappel, le premier
    paramètre est TOUJOURS la requête de l'utilisateur)
    """
    return HttpResponse(
        "Vous avez demandé l'article n° {0} !".format(id_article)    
    )


def addition(request, nombre1, nombre2):    
    total = nombre1 + nombre2

    # Retourne nombre1, nombre2 et la somme des deux au tpl
    return render(request, 'librairie/addition.html', locals())
    


def contact(request):
    # Construire le formulaire, soit avec les données postées,
    # soit vide si l'utilisateur accède pour la première fois
    # à la page.
    form = ContactForm(request.POST or None)
    # Nous vérifions que les données envoyées sont valides
    # Cette méthode renvoie False s'il n'y a pas de données 
    # dans le formulaire ou qu'il contient des erreurs.
    if form.is_valid(): 
        # Ici nous pouvons traiter les données du formulaire
        sujet = form.cleaned_data['sujet']
        message = form.cleaned_data['message']
        envoyeur = form.cleaned_data['envoyeur']
        renvoi = form.cleaned_data['renvoi']

        # Nous pourrions ici envoyer l'e-mail grâce aux données 
        # que nous venons de récupérer
        envoi = True
    
    # Quoiqu'il arrive, on affiche la page du formulaire.
    return render(request, 'librairie/contact.html', locals())
    
def livre(request):
    sauvegarde = False
 
    # Construire le formulaire, soit avec les données postées,
    # soit vide si l'utilisateur accède pour la première fois
    # à la page.
    form = LivreForm(request.POST or None, request.FILES)
    # Nous vérifions que les données envoyées sont valides
    # Cette méthode renvoie False s'il n'y a pas de données 
    # dans le formulaire ou qu'il contient des erreurs.
    if form.is_valid(): 
        
        # Ici nous pouvons traiter les données du formulaire
        titre = form.cleaned_data['titre']
        auteur = form.cleaned_data['auteur']
        resume = form.cleaned_data['resume']
        date = form.cleaned_data['date']
        photo = form.cleaned_data["photo"]
        sauvegarde = True

        # Nous pourrions ici envoyer l'e-mail grâce aux données 
        # que nous venons de récupérer
        
    
    # Quoiqu'il arrive, on affiche la page du formulaire.
    return render(request, 'librairie/livre.html', {
        'form': form, 
        'sauvegarde': sauvegarde
    })

def livreDetails(request, id):
    try:
        livre = Livre.objects.get(id=id)
    except Livre.DoesNotExist:
        raise Http404

    return render(request, 'librairie/livreDetails.html', {'livre': livre})

projet/librairie/templates/librairie/accueil.html
<h1>Bienvenue à la librairie</h1>

{% for livre in derniers_livre %}
    <div class="livre">
    	<h3>{{ livre.titre }}</h3>
    	<p>{{ livre.resume|truncatewords_html:80 }}</p>
        <p><a href="{% url 'livreDetails' livre.id %}">Lire la suite</a></p>
    </div>
{% empty %}
    <p>Aucun livre.</p>
{% endfor %}

projet/librairie/templates/librairie/addition.html
<h1>Ma super calculatrice</h1>
<p>{{ nombre1 }} + {{ nombre2 }}, ça fait <strong>{{ total }}</strong> !<br />
Nous pouvons également calculer la somme dans le template : {{ nombre1|add:nombre2 }}.</p>

projet/librairie/templates/librairie/contact.html
{% if envoi %}Votre message a bien été envoyé !{% endif %}

<form action="{% url "contact" %}" method="post">
	{% csrf_token %}
	<p><label for="id_sujet">Sujet:</label> <input id="id_sujet" type="text" name="sujet" maxlength="100" /></p>
	<p><label for="id_message">Message:</label> <textarea id="id_message" rows="10" cols="40" name="message"></textarea></p>
	<p><label for="id_envoyeur">Votre adresse mail:</label> <input type="text" name="envoyeur" id="id_envoyeur" /></p>
	<p><label for="id_renvoi">Renvoi:</label> <input type="checkbox" name="renvoi" id="id_renvoi" /> <span class="helptext">Cochez si vous souhaitez obtenir une copie du mail envoyé.</span></p>
	<input type="submit" value="Submit" />
</form>

projet/librairie/templates/librairie/livre.html
{% if sauvegarde %}
    <p>livre a bien été enregistré.</p>
{% endif %}

  <form method="post" enctype="multipart/form-data" action=".">
       {% csrf_token %}
    {{ form.as_p }} <br/>
    
    <input type="submit" value="Submit" />
</form>

projet/librairie/templates/librairie/livreDetails.html
<h1>{{ livre.titre }} <span class="small">dans {{ livre.categorie.nom }}</span></h1>
<p class="infos">Rédigé par {{ livre.auteur }}, le {{ livre.date|date:"DATE_FORMAT" }}</p>
<div class="resume">{{ livre.resume|linebreaks }}</div>
<img src="{{ contact.photo.url }}"/>